services:
  backend:
    build: ./backend
    container_name: emotube-backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - ./backend:/app
    depends_on:
      - db # Automatically starts the database when enabled
    networks:
      - emotube-network

  db:
    image: postgres:15
    container_name: emotube-db
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - emotube-network

  frontend:
    build: ./frontend
    container_name: emotube-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    working_dir: /app
    command: bun run start --host
    env_file:
      - .env
    depends_on:
      - backend
    networks:
      - emotube-network

networks:
  emotube-network:

volumes:
  postgres_data:
